### PR TITLE
Feature/us18 change password page

### PR DESCRIPTION
**Pull request by GamzeErdogan**

### CODE REVIEW

**Review by reyhany — APPROVED** [review]
👍

**Review by aslierk — APPROVED** [review]

**Comment by aslierk** [comment]
dikkat gamze. conflict

**Review by aslierk — CHANGES_REQUESTED** [review]
conflict cikmis

**Comment by GamzeErdogan** [comment]
> dikkat gamze. conflict

solved thanks!

**Comment by GamzeErdogan** [comment]
> Conflicte dikkat

Solved thanks

**Review by aslierk — APPROVED** [review]

**Pull request merged**
